# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Monthly profile updating
on:
  schedule:
    - cron: 0 12 21 * *

jobs:
  create_issue:
    name: Create profile updating issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create profile updating issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "thuduyen07"
          labels: "updating"
          title: "profile updating"
          body: |
            ### Tasks

            - [ ] Check all the links
            - [ ] Updating the latest information
                    
            ### Note
            Add things to update for the next time

            - [Note](https://github.com/users/thuduyen07/projects/2)
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
